Repository NMTSolutions/my-travel-companion-react-native, pull requests merged in 2023-05, with the labels that each got.

#3 Mt user info
  .gitignore
  context/UserContext/UserContext.ts
  context/UserContext/UserProvider.tsx
  screens/AuthScreen.tsx
  screens/GetUserInfoScreen.tsx
  screens/OTPScreen.tsx
Labels: enhancement

#4 notificationScreen: created notification screen
  components/BottomNavigation.tsx
  components/Tile.tsx
  routes/availableRoutes.ts
  routes/routes.ts
  screens/NotificationsScreen.tsx
Labels: enhancement

#7 added : user account search
  App.tsx
  context/TravelContext/TravelContext.ts
  context/TravelContext/TravelProvider.tsx
  screens/CompanionsScreen.tsx
  screens/GetUserInfoScreen.tsx
  screens/LoginScreen.tsx
Labels: enhancement

#8 added : companion requests
  components/CompanionTile.tsx
  components/ExpandableTile.tsx
  context/TravelContext/TravelContext.ts
  context/TravelContext/TravelProvider.tsx
  screens/CompanionsScreen.tsx
  screens/DashboardScreen.tsx
  screens/NotificationsScreen.tsx
Labels: enhancement

#9 added: Companions feature
  components/CompanionTile.tsx
  components/ExpandableTile.tsx
  components/LostComapnionTile.tsx
  components/Tile.tsx
  context/TravelContext/TravelContext.ts
  context/TravelContext/TravelProvider.tsx
  context/UserContext/UserContext.ts
  context/UserContext/UserProvider.tsx
  screens/CompanionsScreen.tsx
  screens/DashboardScreen.tsx
  screens/GetUserInfoScreen.tsx
  utilities/utils.ts
Labels: bug, enhancement

#11 chnaged: mapped lists to Flat lists
  components/Grid.tsx
  screens/CompanionsScreen.tsx
  screens/NotificationsScreen.tsx
Labels: bug, enhancement

#12 Added : locations and notifications
  app.json
  context/TravelContext/TravelContext.ts
  context/TravelContext/TravelProvider.tsx
  metro.config.js
  package-lock.json
  package.json
  screens/DashboardScreen.tsx
Labels: bug, documentation, enhancement

#13 added: notification management and user profile data mapping
  components/IconButtonWithBadge.tsx
  components/NotificationTile.tsx
  components/ProfileCard.tsx
  components/Tile.tsx
  context/TravelContext/TravelContext.ts
  context/TravelContext/TravelProvider.tsx
  context/UserContext/UserProvider.tsx
  screens/DashboardScreen.tsx
  screens/NotificationsScreen.tsx
  screens/ProfileScreen.tsx
Labels: bug, documentation, enhancement

#14 resolved: bug
  components/ProfileCard.tsx
Labels: bug
